[package]
name = "EventsListener"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
anyhow = "1.0"
base64 = "0.13"
bech32 = "0.8"
hex = "0.4"
chrono = "0.4"
